version: '3.8'

services:
  # MySQL数据库
  db:
    image: mysql:8.0
    container_name: teachaid-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: teachaid
      MYSQL_ROOT_HOST: '%'
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis缓存
  redis:
    image: redis:7-alpine
    container_name: teachaid-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  # FastAPI后端应用
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: teachaid-app
    ports:
      - "50002:50002"
    environment:
      - DATABASE_URL=mysql+aiomysql://root:root@db:3306/teachaid
      - REDIS_URL=redis://redis:6379/0
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - DEBUG=true
      # AI API密钥（在.env文件中设置）
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - QWEN_API_KEY=${QWEN_API_KEY}
      - YI_API_KEY=${YI_API_KEY}
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:50002/health')"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mysql_data:
  redis_data: