name: CI/CD Pipeline

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 设置Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: 缓存pip依赖
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 代码格式化检查
      run: |
        black --check . || echo "格式检查跳过"
        isort --check-only . || echo "导入排序跳过"

    - name: 构建包
      run: |
        pip install build twine
        python -m build

    - name: 检查包
      run: python -m twine check dist/*

    - name: 上传构建产物
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

  security-scan:
    runs-on: ubuntu-latest
    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 设置Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 运行安全扫描
      run: |
        pip install safety bandit
        safety check || echo "安全检查跳过"
        bandit -r app/ -f json -o bandit-report.json || echo "Bandit扫描跳过"

    - name: 上传安全扫描报告
      uses: actions/upload-artifact@v4
      with:
        name: security-scan-reports
        path: bandit-report.json

  docker-build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 设置Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: 登录到Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: 构建并推送Docker镜像
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/teachaid:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/teachaid:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max