name: Database Migration

on:
  push:
    paths:
      - 'alembic/**'
      - 'app/core/database.py'
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 设置Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 运行数据库迁移
      run: |
        alembic upgrade head
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}

    - name: 验证迁移
      run: |
        alembic current
        alembic history --rev-range head:base